[plugin]
repository = "https://github.com/KangasZ/EurekaHelper.git"
commit = "ddf86b5171bc86d770dadac06dc2644ad679ac86"
owners = ["snorux", "KangasZ"]
project_path = "EurekaHelper"
changelog = """
- SoundEffect to ChatSoundEffect
- Minor updates to Chat message sending to use CS values over direct addresses
"""
