[plugin]
repository = "https://github.com/KangasZ/EurekaHelper.git"
commit = "7f02ad6a780059cbd0a01c90923293bd9274887b"
owners = ["snorux", "KangasZ"]
project_path = "EurekaHelper"
changelog = """
- Added support for patch 7.1 and API 11
- Changed owners
"""